# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/proiect vivado/lab_5/lab_5.cache/wt} [current_project]
set_property parent.project_path {D:/proiect vivado/lab_5/lab_5.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/proiect vivado/lab_5/lab_5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/proiect vivado/lab_2/lab_2.srcs/sources_1/new/SSDComponent.vhd}
  {D:/proiect vivado/lab_2/lab_2.srcs/sources_1/new/MPG.vhd}
  {D:/proiect vivado/lab_5/lab_5.srcs/sources_1/new/MEM.vhd}
  {D:/proiect vivado/lab_5/lab_5.srcs/sources_1/new/ex_unity.vhd}
  {D:/proiect vivado/lab_5/lab_5.srcs/sources_1/new/env.vhd}
  {D:/proiect vivado/lab_5/lab_5.srcs/sources_1/new/Control_Unit.vhd}
  {D:/proiect vivado/lab_5/lab_5.srcs/sources_1/new/ID.vhd}
  {D:/proiect vivado/lab_5/lab_5.srcs/sources_1/new/test_environmental.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/facultate_an2/SEM2/AC/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/facultate_an2/SEM2/AC/Basys3_Master.xdc]


synth_design -top test_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
